Mo' colors
Rudi9719/kbtui pull request #28
Opened 2019-10-22 19:47 UTC by C0DK

Changes:
- Stream is colored now
- Stream is formatted
- Stream has it's own formatting option
- Colors are now a style, and is a struct
- Color struct has a pretty cool functional interface
- colored mentions and PMs
- Every message uses the same function (it's dry!!)
- Colorize errors!
- Create function for visualizing errors
- colorized some of the command output!
- Color is stored in a Style
- Create a Text struct that can use to stylize strings "easily"
- Text can be used to build strings

2019-10-22 20:34 UTC, C0DK commented on colors.go
> +func (txt Text) add(other string) Text {
change to "appendString"

2019-10-22 20:34 UTC, C0DK commented on cmdDelete.go
> +		printError(fmt.Sprintf("There was an error deleting your message."))
remove sprintf

2019-10-22 20:35 UTC, C0DK commented on colors.go
> +func (style Style) withForeground(f color) Style {
change to `s` instead of `style`

2019-10-22 20:56 UTC, Rudi9719 commented
Please make sure you're using the `mage.go` and `.travis.yml` from dev, your PR failed to build, looks like it didn't update the Keybase fwrk?

2019-10-23 12:10 UTC, Rudi9719 reviewed
Please check your `.travis.yml` file, `mage.go` and `cmdDelete.go` - you commented about removing sprintf but didn't?

2019-10-23 12:10 UTC, Rudi9719 commented on cmdDelete.go
> +		printError(fmt.Sprintf("There was an error deleting your message."))
Please do

2019-10-23 12:40 UTC, Rudi9719 requested changes
Please make the changes commented above :+1: Forgot to mark "Request changes" before

2019-10-23 21:39 UTC, C0DK commented
I'l look at the travis stuff soon. not sure what went wrong there :'( but i'll figure it out soon.

But afaik i've fixed all comments and bugs (not mentioned in the commit message :P )

2019-10-23 21:52 UTC, C0DK commented
it passed now!

2019-10-24 11:48 UTC, Rudi9719 approved these changes

2019-10-24 11:49 UTC, merged